language: python

python:
  - "3.7.6"

services:
  - docker

before_install:
  - docker build -t devops-exercise .
  - docker run -d -p 127.0.0.1:5000:5000 -it devops-exercise
  - docker ps -a

script:
  - python tests.py

env:
  global:
    - dsn=$dsn
